name: Parse and Append

on:
  push:
    paths:
      - 'filtered_with_parsed.csv'
      - 'append_master.py'
  workflow_dispatch:    # also allow manual runs from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # so we can push back

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        # if you have extra deps, e.g. requests, bs4, install them:
        # pip install requests beautifulsoup4

    - name: Run parser
      run: |
        python append_master.py filtered_with_parsed.csv

    - name: Commit & push results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add example_of_final_output.csv
        git diff --quiet || git commit -m "🔄 Update parsed output"
        git push
